# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: my-aurora
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/aurora-dx-nvidia-open
image-version: 43

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: kargs
    kargs:
      - intel_iommu=on
      - iommu=pt
      # deliberately OMIT 'rd.driver.pre=vfio_pci' to allow AI mode

  # ---------------------------------------------------------
  # STAGE 1: CLEANUP
  # Remove Firefox first so it doesn't conflict with anything later.
  # ---------------------------------------------------------
  - type: dnf
    install:
      packages:
        - noopenh264 # Prevent removal crash
    remove:
      packages:
        - firefox
        - firefox-langpacks

  # ---------------------------------------------------------
  # STAGE 2: VIRTUALIZATION STACK
  # This is the heavy lifting.
  # ---------------------------------------------------------
  - type: dnf
    repos:
      copr:
        - hikariknight/looking-glass-kvmfr
        - pgaskin/looking-glass-client
    install:
      packages:
        - '@virtualization'    # Pulls in qemu, libvirt, bridge-utils
        - akmod-kvmfr          # Kernel Module
        - looking-glass-client # Viewer App

  # ---------------------------------------------------------
  # STAGE 3: SYSTEM TOOLS
  # Simple userspace apps.
  # ---------------------------------------------------------
  - type: dnf
    repos:
      copr:
        - atim/starship
    install:
      packages:
        - gparted
        - micro
        - starship
        - pv

  # ---------------------------------------------------------
  # STAGE 4: STEAM (RPM)
  # Isolated in its own DNF transaction to manage dependencies.
  # ---------------------------------------------------------
  - type: dnf
    install:
      packages:
        - steam
        - steam-devices

  - type: script
    scripts:
      # - install_kvmfr.sh # Removed as we use akmods now
      - install-brew-packages.sh
      - install_meshroom.sh

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.mozilla.firefox
          - org.gnome.Loupe
          - com.jeffser.Alpaca
          - org.blender.Blender
          - com.bambulab.BambuStudio
          - org.freecadweb.FreeCAD
          - org.gimp.GIMP
          - org.videolan.VLC
          - org.jupyter.JupyterLab
          - io.github.shiftey.Desktop
          - org.openscad.OpenSCAD
          - com.wings3d.WINGS
          - com.visualstudio.code
          - com.raggesilver.BlackBox
          - org.gnome.Boxes
          - com.github.tchx84.Flatseal
      - scope: user

  - type: systemd
    system:
      enabled:
        - docker.service
        - podman.socket
        - libvirtd.service
        - qemu-guest-agent

  - type: signing
