# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: my-aurora
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/aurora-dx-nvidia-open
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      copr:
        - atim/starship
    install:
      packages:
        - micro
        - starship
        - pv
        - virt-manager
        - gparted
    remove:
      packages:
        - firefox
        - firefox-langpacks

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.mozilla.firefox
          - org.gnome.Loupe
          - com.jeffser.Alpaca
          - org.blender.Blender
          - com.bambulab.BambuStudio
          - org.freecadweb.FreeCAD
          - org.gimp.GIMP
          - org.videolan.VLC
          - org.jupyter.JupyterLab
          - io.github.shiftey.Desktop
          - org.openscad.OpenSCAD
          - com.wings3d.WINGS
      - scope: user

  - type: signing
