# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: my-aurora
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/aurora-dx-nvidia-open
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  # 1. Bootloader Args
  - type: kargs
    kargs:
      - intel_iommu=on
      - iommu=pt

  # 2. Standard packages (DNF)
  - type: dnf
    repos:
      copr:
        - atim/starship
        # We need the repo for looking-glass/kvmfr usually.
        # Assuming hikariknight/looking-glass-kvmfr is needed:
        - hikariknight/looking-glass-kvmfr
    install:
      packages:
        - micro
        - starship
        - pv
        - virt-manager
        - gparted
        - "@virtualization"
        - looking-glass-client
        - qemu-guest-agent
        - bridge-utils
        - edk2-ovmf

  # 3. Install KVMFR Source (The "Safe" Way)
  # This installs the package files but prevents the build script from running as root
  - type: script
    name: Install KVMFR Source
    snippets:
      # We install the repo here just in case it wasn't in the dnf module above,
      # but usually, it's better to put the repo in the 'dnf' module.
      - dnf copr enable -y hikariknight/looking-glass-kvmfr
      - dnf install -y --setopt=tsflags=noscripts akmod-kvmfr

  # 4. Compile the Kernel Module
  # This takes the source from Step 3 and builds the driver correctly
  - type: akmods
    base: main
    install:
      - kvmfr

  # 5. Flatpaks (This was malformed in your snippet)
  # I moved this to its own module block where it belongs
  - type: bling
    install:
      - just
      - ublue-os-wallpapers

  # Note: BlueBuild usually handles flatpaks via a 'flatpaks' module,
  # not inside 'akmods'. Assuming you want these installed:
  - type: default-flatpaks
    notify: true
    system:
      install:
        - com.visualstudio.code
        - io.podman_desktop.PodmanDesktop
        - com.raggesilver.BlackBox
        - org.gnome.Boxes
        - com.github.tchx84.Flatseal
        - org.gnome.Ptyxis
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: Flathub

  # 6. Systemd Services
  - type: systemd
    system:
      enabled:
        - docker.service
        - podman.socket
        - libvirtd.service

  - type: signing
