- type: dnf
    repos:
      copr:
        - atim/starship
        # - hikariknight/looking-glass-kvmfr  <-- Comment this out
        # - pgaskin/looking-glass-client      <-- Comment this out
    install:
      packages:
        - micro
        - starship
        - pv
        - virt-manager
        - gparted
        - @virtualization
        # - akmod-kvmfr          <-- Comment this out
        # - looking-glass-client <-- Comment this out
        - qemu-guest-agent
        - bridge-utils
        - edk2-ovmf
