# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: my-aurora
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/aurora-dx-nvidia-open
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  # 1. Bootloader Args
  - type: kargs
    kargs:
      - intel_iommu=on
      - iommu=pt

  # 2. Core Packages
  - type: dnf
    repos:
      copr:
        - atim/starship
        - pgaskin/looking-glass-client
    install:
      packages:
        - micro
        - starship
        - pv
        - virt-manager
        - gparted
        - "@virtualization"   # Quoted for safety
        - looking-glass-client
        - qemu-guest-agent
        - bridge-utils
        - edk2-ovmf
        - ptyxis
    remove:
      packages:
        - firefox
        - firefox-langpacks

  # 3. Flatpaks
  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.mozilla.firefox
          - org.gnome.Loupe
          - com.jeffser.Alpaca
          - org.blender.Blender
          - com.bambulab.BambuStudio
          - org.freecadweb.FreeCAD
          - org.gimp.GIMP
          - org.videolan.VLC
          - org.jupyter.JupyterLab
          - io.github.shiftey.Desktop
          - org.openscad.OpenSCAD
          - com.wings3d.WINGS
          - com.visualstudio.code
          - io.podman_desktop.PodmanDesktop
          - com.raggesilver.BlackBox
          - org.gnome.Boxes
          - com.github.tchx84.Flatseal
      - scope: user

  # 4. Manual Scripts (Homebrew & KVMFR Driver)
  - type: script
    scripts:
      - install-brew-packages.sh  # <--- FIXED PATH (was /usr/local/bin)
      - install_kvmfr.sh

  - type: systemd
    system:
      enabled:
        - docker.service
        - podman.socket
        - libvirtd.service

  - type: signing
