# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: my-aurora
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/aurora-dx-nvidia-open
image-version: latest

modules:
  - type: files
    files:
    - source: system
      destination: /

  - type: dnf
    repos:
    copr:
        - atim/starship
    install:
    packages:
        - micro
        - starship
        - pv
        - virt-manager
        - gparted
        - "@virtualization"
    remove:
    packages:
        - firefox
        - firefox-langpacks

  - type: default-flatpaks
    configurations:
    - notify: true
        scope: system
        install:
        - org.mozilla.firefox
        - org.gnome.Loupe
        - com.jeffser.Alpaca
        - org.blender.Blender
        - com.bambulab.BambuStudio
        - org.freecadweb.FreeCAD
        - org.gimp.GIMP
        - org.videolan.VLC
        - org.jupyter.JupyterLab
        - io.github.shiftey.Desktop
        - org.openscad.OpenSCAD
        - com.wings3d.WINGS
        # DX Apps
        - com.visualstudio.code
        - io.podman_desktop.PodmanDesktop
        - com.raggesilver.BlackBox
        - org.gnome.Boxes
        - com.github.tchx84.Flatseal
        - org.gnome.Ptyxis
    - scope: user
        []
  - type: homebrew
    # Taps (Repositories)
    install:
        - brew install charmbracelet/tap
        - brew install gptscript-ai/tap
        - brew install blockprotocol/tap
        # Packages (Use 'pkgs' for strict schema compliance)
    packages:
        - brew install uv
        - brew install ripgrep
        - brew install bat
        - brew install eza
        - brew install fzf
        - brew install zoxide
        - brew install walk
        - brew install syft
        - brew install yq
        - brew install aichat
        - brew install block-goose-cli
        - brew install gemini-cli
        - brew install mods
        - brew install ramalama
        - brew install llm
        - brew install opencode
        - brew install qwen-code
        - brew install whisper-cpp
        - brew install gptscript-ai/tap/clio
        - brew install charmbracelet/tap/crush
        - brew install --cask codex
  - type: systemd
    system:
      enabled:
        - docker.service
        - podman.socket
        - libvirtd.service

  - type: signing
